import { isBoilerplate } from "@harmeese/shared/boilerplates.js";
import type { Boilerplate } from "@harmeese/shared/types.js";

export interface LandingTemplate {
  brand: string;
  title: string;
  description: string;
  cta: string;
  metric: string;
  metricLabel: string;
  sectionTitle: string;
  cards: Array<{ title: string; text: string }>;
  why: Array<{ title: string; text: string }>;
  formTitle: string;
  interestOptions: string[];
  footer: string;
}

const templates: Record<Boilerplate, LandingTemplate> = {
  "ai-training-company": {
    brand: "NeuralEdge Academy",
    title: "AI Training Programs for Modern Teams",
    description: "Role-specific GenAI and agentic AI workshops that help teams move from experimentation to repeatable business outcomes.",
    cta: "Request Corporate Workshop",
    metric: "4.8/5",
    metricLabel: "Average workshop rating across enterprise cohorts",
    sectionTitle: "Programs",
    cards: [
      { title: "GenAI for Finance Teams", text: "Forecasting workflows, controls, reporting copilots, and audit-safe prompt patterns." },
      { title: "GenAI for HR Teams", text: "Policy assistants, talent workflows, employee comms, and responsible AI practices." },
      { title: "GenAI for Sales & Marketing Teams", text: "Research, campaign production, account planning, and brand-safe content systems." },
      { title: "Agentic AI for Engineering Teams", text: "Spec-driven coding agents, code review workflows, testing loops, and deployment guardrails." }
    ],
    why: [
      { title: "Role-specific", text: "Every workshop is mapped to the daily workflows of the team in the room." },
      { title: "Hands-on", text: "Teams leave with reusable prompts, governance checklists, and prototype workflows." },
      { title: "Measured", text: "Programs include adoption metrics and a practical next-step roadmap." }
    ],
    formTitle: "Request a corporate workshop",
    interestOptions: ["Executive AI workshop", "Finance team training", "HR team training", "Sales and marketing training", "Engineering agentic AI training"],
    footer: "NeuralEdge Academy demo site generated by Harmeese Cloud Builder."
  },
  "saas-landing-page": {
    brand: "Northstar Ops",
    title: "Operations Software That Keeps Teams Moving",
    description: "A focused SaaS landing page for teams that need clean workflows, visibility, and AI-assisted follow-through.",
    cta: "Request Product Demo",
    metric: "38%",
    metricLabel: "Average admin time reduced in pilot teams",
    sectionTitle: "Platform",
    cards: [
      { title: "Workflow Inbox", text: "Route requests, approvals, and exceptions into one accountable operating queue." },
      { title: "AI Summaries", text: "Turn long updates and customer notes into clear next steps." },
      { title: "Team Dashboards", text: "Track volume, ownership, bottlenecks, and response quality." },
      { title: "Integrations", text: "Connect mail, calendar, and internal systems with controlled automation hooks." }
    ],
    why: [
      { title: "Fast to trial", text: "Launch a credible demo funnel with product copy and lead capture." },
      { title: "Operational tone", text: "Designed for serious buyers comparing tools." },
      { title: "AI-ready", text: "Every form can route into an AI handling workflow." }
    ],
    formTitle: "Request a product demo",
    interestOptions: ["Product demo", "Pricing", "Pilot program", "Integration discussion", "Security review"],
    footer: "Northstar Ops demo site generated by Harmeese Cloud Builder."
  },
  "course-platform": {
    brand: "SkillForge Studio",
    title: "Launch Cohort-Based Courses With AI Support",
    description: "A course platform starter for instructors, bootcamps, and training teams that need a polished enrollment path.",
    cta: "Join the Next Cohort",
    metric: "1,200+",
    metricLabel: "Learners served across live cohorts",
    sectionTitle: "Featured Courses",
    cards: [
      { title: "AI Foundations", text: "A practical introduction to AI tools, workflows, and responsible usage." },
      { title: "Prompt Systems", text: "Build repeatable prompt libraries for research, writing, and analysis." },
      { title: "Automation Lab", text: "Connect forms, docs, email, and calendars into useful learning workflows." },
      { title: "Capstone Studio", text: "Ship a real project with feedback, demos, and portfolio assets." }
    ],
    why: [
      { title: "Cohort-ready", text: "Clear outcomes, social proof, and enrollment capture." },
      { title: "Instructor-led", text: "Position live sessions, office hours, and project reviews." },
      { title: "AI backend", text: "Learner questions and enrollment forms can be triaged by AI." }
    ],
    formTitle: "Ask about enrollment",
    interestOptions: ["Next cohort", "Team training", "Private class", "Scholarship", "Curriculum details"],
    footer: "SkillForge Studio demo site generated by Harmeese Cloud Builder."
  },
  "personal-portfolio": {
    brand: "Avery Chen",
    title: "Product Designer and Builder for AI-Native Teams",
    description: "A personal website for showcasing selected work, writing, services, and an AI-assisted contact workflow.",
    cta: "Start a Conversation",
    metric: "12",
    metricLabel: "Product launches shaped from idea to release",
    sectionTitle: "Selected Work",
    cards: [
      { title: "AI Research Workspace", text: "Designed a focused analysis tool for strategy and product teams." },
      { title: "Founder Dashboard", text: "Built a metrics console for funnel, revenue, and customer signals." },
      { title: "Design Systems", text: "Created component standards for faster product delivery." },
      { title: "Writing", text: "Notes on AI UX, product taste, and practical prototyping." }
    ],
    why: [
      { title: "Sharp positioning", text: "A polished home for your work, services, and point of view." },
      { title: "Lead capture", text: "Contact requests are summarized and prioritized by AI." },
      { title: "Easy to evolve", text: "Use Telegram changes to queue new case studies or sections." }
    ],
    formTitle: "Contact Avery",
    interestOptions: ["Project inquiry", "Portfolio review", "Speaking", "Advisory", "Collaboration"],
    footer: "Personal portfolio generated by Harmeese Cloud Builder."
  },
  "creator-link-in-bio": {
    brand: "Mira Makes",
    title: "Creator Hub for Videos, Essays, Products, and Sponsors",
    description: "A link-in-bio style website that gives creators more control than a profile page and routes every inquiry to AI.",
    cta: "Work With Mira",
    metric: "86K",
    metricLabel: "Monthly audience across channels",
    sectionTitle: "Featured Links",
    cards: [
      { title: "Latest Video", text: "A featured content slot for the newest launch or episode." },
      { title: "Newsletter", text: "A clear subscription CTA with AI-assisted follow-up." },
      { title: "Digital Products", text: "Promote templates, courses, downloads, and paid resources." },
      { title: "Sponsor Kit", text: "Capture brand inquiries and draft sponsor replies automatically." }
    ],
    why: [
      { title: "Own the funnel", text: "Move beyond a generic profile page." },
      { title: "Sponsor-ready", text: "Qualify partnership requests with AI summaries." },
      { title: "Fast updates", text: "Queue link and copy changes from Telegram." }
    ],
    formTitle: "Send an inquiry",
    interestOptions: ["Sponsorship", "Collaboration", "Newsletter", "Product support", "Speaking"],
    footer: "Creator hub generated by Harmeese Cloud Builder."
  },
  "consultant-website": {
    brand: "Rowan Strategy",
    title: "Independent Strategy Consulting for Growing Teams",
    description: "A consultant website starter with services, credibility, and an AI backend that qualifies serious inquiries.",
    cta: "Book a Strategy Call",
    metric: "$24M",
    metricLabel: "Pipeline influenced across client engagements",
    sectionTitle: "Services",
    cards: [
      { title: "Positioning", text: "Clarify your market, story, and buyer-facing offer." },
      { title: "GTM Systems", text: "Build repeatable sales, marketing, and customer learning loops." },
      { title: "Executive Advisory", text: "Support decisions with crisp analysis and operating cadence." },
      { title: "AI Enablement", text: "Introduce AI workflows without losing quality control." }
    ],
    why: [
      { title: "Senior judgment", text: "Present a premium advisory offer with proof points." },
      { title: "Qualified leads", text: "AI summarizes budgets, timing, and fit." },
      { title: "Calendar-ready", text: "Maton hooks can queue follow-up scheduling." }
    ],
    formTitle: "Book a strategy call",
    interestOptions: ["Advisory", "Positioning", "GTM systems", "AI enablement", "Workshop"],
    footer: "Consultant website generated by Harmeese Cloud Builder."
  },
  "local-service-business": {
    brand: "Brightline Home Services",
    title: "Reliable Local Services With Fast AI-Assisted Quotes",
    description: "A local business website for service areas, trust signals, reviews, and quote requests handled by an AI backend.",
    cta: "Request a Quote",
    metric: "24h",
    metricLabel: "Typical quote turnaround for qualified requests",
    sectionTitle: "Services",
    cards: [
      { title: "Home Repairs", text: "Small repairs, punch lists, and maintenance visits." },
      { title: "Installations", text: "Fixtures, shelving, appliances, and light upgrades." },
      { title: "Preventive Care", text: "Seasonal maintenance plans for busy homeowners." },
      { title: "Emergency Triage", text: "AI collects details and prioritizes urgent issues." }
    ],
    why: [
      { title: "Local trust", text: "Highlight reviews, service areas, and clear response expectations." },
      { title: "Better intake", text: "AI captures the issue, urgency, location, and next step." },
      { title: "Less admin", text: "Queue follow-ups, calendar holds, and reply drafts." }
    ],
    formTitle: "Request a quote",
    interestOptions: ["Repair", "Installation", "Maintenance plan", "Urgent request", "Estimate"],
    footer: "Local service site generated by Harmeese Cloud Builder."
  },
  "event-speaker-page": {
    brand: "Jordan Vale",
    title: "Keynotes and Workshops on AI, Product, and Teams",
    description: "A speaker page with talk topics, credibility, media-kit positioning, and AI-assisted booking intake.",
    cta: "Invite Jordan to Speak",
    metric: "60+",
    metricLabel: "Talks delivered for product and leadership audiences",
    sectionTitle: "Talk Topics",
    cards: [
      { title: "AI-Native Workflows", text: "How teams can adopt AI without chaos or quality loss." },
      { title: "Product Taste", text: "Decision-making principles for better software and services." },
      { title: "Agentic Teams", text: "How human and AI operators coordinate work." },
      { title: "Executive Workshops", text: "Private sessions for leadership teams planning AI adoption." }
    ],
    why: [
      { title: "Booker-friendly", text: "Clear topics, format options, and inquiry details." },
      { title: "AI triage", text: "Summarize event date, audience, budget, and fit." },
      { title: "Media-ready", text: "Queue updates for bio, headshots, and talk abstracts." }
    ],
    formTitle: "Send a speaking inquiry",
    interestOptions: ["Keynote", "Workshop", "Panel", "Podcast", "Private executive session"],
    footer: "Speaker page generated by Harmeese Cloud Builder."
  },
  "nonprofit-campaign": {
    brand: "Open Futures Fund",
    title: "A Campaign Site for Donors, Volunteers, and Community Action",
    description: "A nonprofit campaign starter that explains the mission, captures supporter intent, and routes follow-up through AI.",
    cta: "Support the Campaign",
    metric: "3,800",
    metricLabel: "Community members reached this year",
    sectionTitle: "Campaign Priorities",
    cards: [
      { title: "Education Access", text: "Programs that connect learners with mentors, tools, and resources." },
      { title: "Volunteer Network", text: "Coordinate local supporters and match them to specific needs." },
      { title: "Donor Updates", text: "Share transparent impact, milestones, and next funding goals." },
      { title: "Community Events", text: "Capture interest and queue calendar follow-ups." }
    ],
    why: [
      { title: "Mission clarity", text: "Make the cause understandable in the first viewport." },
      { title: "Supporter routing", text: "AI classifies donors, volunteers, partners, and press." },
      { title: "Action-oriented", text: "Every inquiry creates a next step instead of a dead-end form." }
    ],
    formTitle: "Get involved",
    interestOptions: ["Donate", "Volunteer", "Partner", "Attend event", "Media inquiry"],
    footer: "Nonprofit campaign site generated by Harmeese Cloud Builder."
  }
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function selectedTemplate(boilerplate?: Boilerplate): LandingTemplate {
  const id = boilerplate ?? (isBoilerplate(process.env.BOILERPLATE) ? process.env.BOILERPLATE : "ai-training-company");
  return templates[id];
}

export function landingPage(success = false, boilerplate?: Boilerplate): string {
  const template = selectedTemplate(boilerplate);
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(template.brand)}</title>
    <style>
      :root { --ink:#162126; --muted:#5e6972; --line:#d8e0e6; --accent:#0f766e; --accent2:#c2410c; --soft:#eef5f4; --dark:#10201f; }
      * { box-sizing:border-box; }
      body { margin:0; font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; color:var(--ink); background:#f7f9fb; }
      header { background:var(--dark); color:white; }
      .wrap { width:min(1120px, calc(100vw - 32px)); margin:0 auto; }
      nav { display:flex; justify-content:space-between; align-items:center; padding:18px 0; gap:16px; }
      nav strong { font-size:1.05rem; }
      nav a { color:white; text-decoration:none; font-weight:800; }
      .hero { display:grid; grid-template-columns:1.1fr .9fr; gap:38px; align-items:center; min-height:520px; padding:42px 0 56px; }
      h1 { font-size:clamp(2.35rem, 6vw, 4.9rem); line-height:1; margin:0 0 18px; letter-spacing:0; }
      .hero p { color:#cfe0dd; font-size:1.15rem; line-height:1.6; margin:0 0 26px; }
      .cta { display:inline-block; background:#f2b84b; color:#1b1b16; padding:14px 18px; border-radius:7px; text-decoration:none; font-weight:900; }
      .hero-media { min-height:360px; border-radius:8px; background:linear-gradient(135deg,#183936,#0f766e 55%,#f2b84b); display:grid; place-items:center; color:white; border:1px solid rgba(255,255,255,.18); }
      .metric { width:78%; background:rgba(255,255,255,.12); border:1px solid rgba(255,255,255,.2); border-radius:8px; padding:22px; backdrop-filter:blur(8px); }
      .metric b { display:block; font-size:2.2rem; }
      section { padding:58px 0; }
      h2 { font-size:2rem; margin:0 0 20px; }
      .grid { display:grid; grid-template-columns:repeat(4, 1fr); gap:16px; }
      .card { background:white; border:1px solid var(--line); border-radius:8px; padding:20px; min-height:170px; }
      .card h3 { margin:0 0 10px; }
      .card p, .why p { color:var(--muted); line-height:1.55; }
      .why { display:grid; grid-template-columns:repeat(3, 1fr); gap:18px; }
      .form-band { background:var(--soft); border-top:1px solid var(--line); }
      form { background:white; border:1px solid var(--line); border-radius:8px; padding:22px; display:grid; grid-template-columns:1fr 1fr; gap:14px; }
      label { display:grid; gap:7px; font-weight:800; color:var(--muted); font-size:.9rem; }
      input, select, textarea { width:100%; border:1px solid var(--line); border-radius:7px; min-height:44px; padding:10px 12px; font:inherit; color:var(--ink); background:white; }
      textarea, .full { grid-column:1 / -1; }
      button { border:0; border-radius:7px; min-height:46px; background:var(--accent); color:white; font:inherit; font-weight:900; cursor:pointer; }
      .notice { border-left:5px solid var(--accent); background:white; padding:14px; border-radius:7px; margin-bottom:18px; font-weight:800; }
      footer { padding:28px 0; color:var(--muted); }
      @media (max-width:850px) { .hero, .grid, .why, form { grid-template-columns:1fr; } textarea, .full { grid-column:auto; } }
    </style>
  </head>
  <body>
    <header>
      <div class="wrap">
        <nav><strong>${escapeHtml(template.brand)}</strong><a href="#lead">${escapeHtml(template.cta)}</a></nav>
        <div class="hero">
          <div>
            <h1>${escapeHtml(template.title)}</h1>
            <p>${escapeHtml(template.description)}</p>
            <a class="cta" href="#lead">${escapeHtml(template.cta)}</a>
          </div>
          <div class="hero-media" aria-label="Site metric preview">
            <div class="metric"><b>${escapeHtml(template.metric)}</b><span>${escapeHtml(template.metricLabel)}</span></div>
          </div>
        </div>
      </div>
    </header>

    <main>
      <section>
        <div class="wrap">
          <h2>${escapeHtml(template.sectionTitle)}</h2>
          <div class="grid">
            ${template.cards.map((card) => `<article class="card"><h3>${escapeHtml(card.title)}</h3><p>${escapeHtml(card.text)}</p></article>`).join("")}
          </div>
        </div>
      </section>

      <section>
        <div class="wrap">
          <h2>Why this works</h2>
          <div class="why">
            ${template.why.map((item) => `<div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.text)}</p></div>`).join("")}
          </div>
        </div>
      </section>

      <section id="lead" class="form-band">
        <div class="wrap">
          <h2>${escapeHtml(template.formTitle)}</h2>
          ${success ? '<div class="notice">Thanks. Your request was received and the AI backend is preparing the next step.</div>' : ""}
          <form method="post" action="/lead">
            <label>Name<input name="name" required /></label>
            <label>Company<input name="company" required /></label>
            <label>Email<input name="email" type="email" required /></label>
            <label>Team size<input name="teamSize" placeholder="25" /></label>
            <label class="full">Interest<select name="interest" required>${template.interestOptions.map((option) => `<option>${escapeHtml(option)}</option>`).join("")}</select></label>
            <label class="full">Message<textarea name="message" rows="5" placeholder="Tell us what you need. The AI backend will route the next step."></textarea></label>
            <button class="full" type="submit">Send request</button>
          </form>
        </div>
      </section>
    </main>
    <footer><div class="wrap">${escapeHtml(template.footer)}</div></footer>
  </body>
</html>`;
}
